# Generated by Django 5.1.2 on 2024-10-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_tipo_vaga_proprietario_tipo_prop'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='senha',
            field=models.CharField(default='senha_temporaria', max_length=128),
            preserve_default=False,
        ),
    ]
