# Generated by Django 5.1.2 on 2024-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_proprietario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietario',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
