# Generated by Django 5.1.2 on 2024-11-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_proprietario_groups_proprietario_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navegacao',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='proprietario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='veiculo',
        ),
        migrations.DeleteModel(
            name='Monitoramento',
        ),
        migrations.DeleteModel(
            name='Navegacao',
        ),
        migrations.DeleteModel(
            name='Proprietario',
        ),
        migrations.DeleteModel(
            name='Vaga',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
