# Generated by Django 5.1.2 on 2024-11-11 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0007_remove_navegacao_vaga_remove_proprietario_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vaga', models.CharField(max_length=10, unique=True)),
                ('tipo_vaga', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('deficiente', 'Deficiente')], max_length=20)),
                ('ocupada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas', models.CharField(max_length=100)),
                ('instrucoes', models.TextField()),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('inicio_reserva', models.DateTimeField()),
                ('fim_reserva', models.DateTimeField()),
                ('vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.vaga')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_vaga', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vaga')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.veiculo')),
            ],
        ),
    ]
